
name: Bump Release Version

on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - 'cocodemo.podspec'
      - '*.md'
      - 'cocodemo/Classes/Version.swift'
    branches: 
      - public-release/*

jobs:
  bump_version_spec:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_ACTIONS }}
      
    - name: Fetch branch name
      id: branch
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      
    - name: Extract version number
      id: version
      run: echo "::set-output name=version::${{ steps.branch.outputs.branch#public-release/ }}"
      
    - name: Bump Version
      run: |
           chmod +x ./scripts/bump_version.sh
           ./scripts/bump_version.sh ${{ steps.version.outputs.version }}

    - name: Commit changes
      run: |
           git config user.name ${{ github.actor }}
           git config user.email ${{ github.actor }}@users.noreply.github.com
           git add cocodemo.podspec 
           git add cocodemo/Classes/Version.swift
           git commit -m "[AUTOMATED] Public Release ${{ steps.version.outputs.version }}"
           git push origin