
name: Internal Release

on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - 'cocodemo.podspec'
      - '*.md'
    branches: 
      - release/*

jobs:
  deploy_private_pod:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_ACTIONS }}
      
    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Bump Version
      run: |
           chmod +x ./scripts/bump_version.sh
           ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}" "$(git rev-parse --short "$GITHUB_SHA")"
    
    - name: Commit changes
      run: |
           git config user.name ${{ github.actor }}
           git config user.email ${{ github.actor }}@users.noreply.github.com
           git add cocodemo.podspec 
           git add cocodemo/Classes/Version.swift
           git commit -m "[AUTOMATED] Private Release ${{ steps.previoustag.outputs.tag }}.$(git rev-parse --short $GITHUB_SHA)"
           git push origin

    - name: Push updated spec file
      run: |
           pod repo add private_spec https://github.com/skyflow-bharti/cocodemo-private-spec.git
           pod repo push private_spec ./cocodemo.podspec --allow-warnings
           echo "Published as Private pod"
