name: Public Beta Release

on:
  push:
    tags: '*.*.*-beta.*'

jobs:
  deploy_private_pod:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_ACTIONS }}

    - name: Get the current tag
      id: check_step
      run: |
        tag_name=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
        commit_hash=$(git rev-list --parents -n 1 "${tag_name}" | awk '{print $2}')
        branch_name=$(git branch --contains "${commit_hash}" | grep -v "detached HEAD" | head -1 | awk '{print $NF}')
        echo "Branch name: ${branch_name}"
        branch=${branch_name}
        echo "::set-output name=branch::$branch"
        echo "Branch is $branch."
      
    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Bump Version
      run: |
           chmod +x ./scripts/bump_version.sh
           ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}"
    
    - name: Commit changes
      run: |
           git config user.name ${{ github.actor }}
           git config user.email ${{ github.actor }}@users.noreply.github.com
           git branch -f ${{ steps.check_step.outputs.branch }} origin/${{ steps.check_step.outputs.branch }}
           git checkout ${{ steps.check_step.outputs.branch }}
           git add cocodemo.podspec
           git commit -m "[AUTOMATED] Beta Release ${{ steps.check_step.outputs.branch }}"
           git push origin ${{ steps.check_step.outputs.branch }}
    
    - name: Deploy to Cocoapods
      run: |
           set -eo pipefail
           pod lib lint --allow-warnings
           pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
