name: Public Beta Release

on:
  push:
    tags: '*.*.*-beta.*'

jobs:
  deploy_private_pod:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_ACTIONS }}

    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
      id: extract_branch    
      
    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Bump Version
      run: |
           chmod +x ./scripts/bump_version.sh
           ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}"
    
    - name: Commit changes
      run: |
           git config user.name ${{ github.actor }}
           git config user.email ${{ github.actor }}@users.noreply.github.com
           git branch -f ${{ steps.extract_branch.outputs.branch }} origin/${{ steps.extract_branch.outputs.branch }}
           git checkout steps.extract_branch.outputs.branch
           git add cocodemo.podspec
           git commit -m "[AUTOMATED] Beta Release ${{ steps.extract_branch.outputs.branch }}"
           git push origin ${{ steps.extract_branch.outputs.branch }}
    
    - name: Deploy to Cocoapods
      run: |
           set -eo pipefail
           pod lib lint --allow-warnings
           pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
